/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HTTPproxy_constants.h"

namespace proxyspace {

const HTTPproxyConstants g_HTTPproxy_constants;

HTTPproxyConstants::HTTPproxyConstants() {
}

} // namespace

