// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HTTPproxy.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <iostream>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::proxyspace;

class HTTPproxyHandler : virtual public HTTPproxyIf {
 public:
  HTTPproxyHandler() {
    std::cout<<"Server is up and running...\n";
  }

  void request(response& _return, const std::string& url) {
    _return.response_code = 7;
    _return.document = "Sample HTML response\n<html>\n\t<head>"
            "\n\t\tThis is the head\n\t</head>\n</html>\n";

    std::cout<<"Requested URL is : "<<url<<"\n";
  }

  void shutdown() {
    // Your implementation goes here
    printf("Shutting down...\n");
    exit(0);
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<HTTPproxyHandler> handler(new HTTPproxyHandler());
  shared_ptr<TProcessor> processor(new HTTPproxyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

