/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HTTPproxy_CONSTANTS_H
#define HTTPproxy_CONSTANTS_H

#include "HTTPproxy_types.h"

namespace proxyspace {

class HTTPproxyConstants {
 public:
  HTTPproxyConstants();

};

extern const HTTPproxyConstants g_HTTPproxy_constants;

} // namespace

#endif
